version: '3.9'

services:
  
  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_USER=lumidev
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=sistema_de_projetos
    volumes:
      - postgres_data:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
    postgres_data:
        driver: local

networks:
  sistema-de-projetos-network:
    driver: brigde